#!/bin/sh
#
# convert ImageDisk IMD format disk images to HFE format
#
# HFE format images are useful for HxC or FlashFloppy USB disk emulators
#
# requires disk-analyse (part of Disk-Utilities) https://github.com/keirf/Disk-Utilities
#
# more details at https://www.richardloxley.com/2018/04/27/osborne-restoration-part-16-transferring-cpm-software


if [ $# -ne 2 ]
then
        echo "Usage: $0 <source> <destination>"
        exit 1
fi

# disk-analyse infers format from file suffix

TEMP_SRC="temp_image_$$.imd"
TEMP_DEST="temp_image_$$.hfe"

cp "$1" $TEMP_SRC

disk-analyse -q $TEMP_SRC $TEMP_DEST

rm $TEMP_SRC
mv $TEMP_DEST "$2"

